In [10]:
import plotly.plotly as py
import csv
import pandas as pd
import plotly

In [2]:
df_tudo = pd.read_csv("../CSVs/tabela_segundo_passo_merge_assinaturas_coordenadas.csv")

In [3]:
# aqui mostra a quantidade de url assinadas em cada pais
df_gru = df_tudo["url"].groupby([df_tudo["pais"],df_tudo["latitude"],df_tudo["longitude"]],sort=True).count().sort_values(ascending=False)
df_gru.to_csv("grupos paises.csv")

In [4]:
df_gru

pais                  latitude    longitude
United States          37.090240  -95.71289     454
Brazil                -14.235004  -51.92520     179
Australia             -25.274398   133.77513     42
United Kingdom         55.378051  -3.43597       37
India                  20.593684   78.96280      21
Taiwan                 23.697810   120.96051     17
Colombia               4.570868   -74.29733      16
Russia                 61.524010   105.31875      8
China                  35.861660   104.19539      7
Philippines            12.879721   121.77401      6
Israel                 31.046051   34.85161       5
Italy                  41.871940   12.56730       5
Greece                 39.074208   21.82431       4
Ukraine                48.379433   31.16550       4
Ireland                53.412910  -8.24380        4
Argentina             -38.416097  -63.61667       4
South Africa          -30.559482   22.93750       3
Bangladesh             23.684994   90.35633       3
Turkey                 38.963745   35.24332       3
Nigeria                9.081999    8.67527        3
Czech Republic         49.817492   15.47296       2
Hong Kong              22.396428   114.10949      2
Vietnam                14.058324   108.27719      2
Malta                  35.937496   14.37541       2
Tunisia                33.886917   9.53749        2
Sri Lanka              7.873054    80.77179       2
Moldova                47.411631   28.36988       2
Slovakia               48.669026   19.69902       2
Oman                   21.512583   55.92325       2
Seychelles            -4.679574    55.49197       2
Mauritania             21.007890  -10.94083       1
Ghana                  7.946527   -1.02319        1
United Arab Emirates   23.424076   53.84781       1
Belarus                53.709807   27.95338       1
Singapore              1.352083    103.81983      1
Romania                45.943161   24.96670       1
Dominican Republic     18.735693  -70.16265       1
Gibraltar              36.137741  -5.34537        1
Malaysia               4.210484    101.97576      1
Poland                 51.919438   19.14513       1
Papua New Guinea      -6.314993    143.95550      1
Netherlands            52.132633   5.29126        1
Mongolia               46.862496   103.84665      1
Latvia                 56.879635   24.60318       1
Lebanon                33.854721   35.86228       1
Macedonia [FYROM]      41.608635   21.74527       1
Madagascar            -18.766947   46.86910       1
Algeria                28.033886   1.65962        1
Name: url, dtype: int64

In [15]:
df = pd.read_csv("grupos paises.csv",names=["pais","latitude","longitude","quantidade"])

In [16]:
df

                    pais   latitude  longitude  quantidade
0          United States  37.090240  -95.71289         454
1                 Brazil -14.235004  -51.92520         179
2              Australia -25.274398  133.77513          42
3         United Kingdom  55.378051   -3.43597          37
4                  India  20.593684   78.96280          21
5                 Taiwan  23.697810  120.96051          17
6               Colombia   4.570868  -74.29733          16
7                 Russia  61.524010  105.31875           8
8                  China  35.861660  104.19539           7
9            Philippines  12.879721  121.77401           6
10                Israel  31.046051   34.85161           5
11                 Italy  41.871940   12.56730           5
12                Greece  39.074208   21.82431           4
13               Ukraine  48.379433   31.16550           4
14               Ireland  53.412910   -8.24380           4
15             Argentina -38.416097  -63.61667           4
16          South Africa -30.559482   22.93750           3
17            Bangladesh  23.684994   90.35633           3
18                Turkey  38.963745   35.24332           3
19               Nigeria   9.081999    8.67527           3
20        Czech Republic  49.817492   15.47296           2
21             Hong Kong  22.396428  114.10949           2
22               Vietnam  14.058324  108.27719           2
23                 Malta  35.937496   14.37541           2
24               Tunisia  33.886917    9.53749           2
25             Sri Lanka   7.873054   80.77179           2
26               Moldova  47.411631   28.36988           2
27              Slovakia  48.669026   19.69902           2
28                  Oman  21.512583   55.92325           2
29            Seychelles  -4.679574   55.49197           2
30            Mauritania  21.007890  -10.94083           1
31                 Ghana   7.946527   -1.02319           1
32  United Arab Emirates  23.424076   53.84781           1
33               Belarus  53.709807   27.95338           1
34             Singapore   1.352083  103.81983           1
35               Romania  45.943161   24.96670           1
36    Dominican Republic  18.735693  -70.16265           1
37             Gibraltar  36.137741   -5.34537           1
38              Malaysia   4.210484  101.97576           1
39                Poland  51.919438   19.14513           1
40      Papua New Guinea  -6.314993  143.95550           1
41           Netherlands  52.132633    5.29126           1
42              Mongolia  46.862496  103.84665           1
43                Latvia  56.879635   24.60318           1
44               Lebanon  33.854721   35.86228           1
45     Macedonia [FYROM]  41.608635   21.74527           1
46            Madagascar -18.766947   46.86910           1
47               Algeria  28.033886    1.65962           1

In [7]:
df.to_csv("../CSVs/total_de_paises_URLs_gov.csv")

In [19]:
plotly.tools.set_credentials_file(username='AlisonLucio', api_key='A4dXLP8IxnUvDOGm4U6O')

In [23]:
df['text'] = df['pais'] + '<br>URLs que tenham .gov ' + (df['quantidade']).astype(str)
limits = [(0,10),(11,25),(26,45),(46,100),(101,200)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","lightgrey"]
cities = []
scale = 5

for i in range(len(limits)):
    lim = limits[i]
    df_sub = df[lim[0]:lim[1]]
    city = dict(
        type = 'scattergeo',
        #locationmode = 'USA-states',
        lon = df_sub['longitude'],
        lat = df_sub['latitude'],
        text = df_sub['text'],
        marker = dict(
            size = df_sub['quantidade'] *scale,
            # sizeref = 2. * max(df_sub['pop']/scale) / (25 ** 2),
            color = colors[i],
            line = dict(width=0.5, color='rgb(40,40,40)'),
            sizemode = 'area'
        ),
        name = '{0} - {1}'.format(lim[0],lim[1]) )
    cities.append(city)

layout = dict(
        title = 'Quantidade de URLs com .gov <br>(Click na legenda para ver detalhes)',
        showlegend = True,
        geo = dict(
            scope='world',
            projection=dict( type = 'natural earth'),
            showland = True,
            landcolor = 'rgb(217, 217, 217)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict(data=cities, layout=layout)
py.iplot(fig, validate=False, filename='Quantidade de URLs .gov com com open, data ou trans')