In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import csv
import seaborn as sns
import matplotlib.pyplot as plt
import gc
from datetime import datetime
import json
import urllib.request
import numpy as np

In [3]:
# crio um dataframe do csv com as url que contem data, open ou transp como parte da url
df_gov = pd.read_csv('../CSVs/subscriptions.csv', delimiter=',')

In [4]:
# verificando se tem dados do Reino Unido
init = "gb"
df_gov.query("initials == @init")

,Unnamed: 0,id,url,date_catch,index_fraction,initials,country,platform_opendata
21,1323,44629,https://guidance.data.gov.uk,2018-09-12 16:30:46,4795,gb,Reino Unido,NaN
24,1350,46929,https://www.thetransat.com/venues/view/www.ply...,2018-09-12 18:02:03,4854,gb,Reino Unido,NaN
73,3598,79746,https://dataarchitecture.blog.gov.uk,2018-08-28 00:06:28,1189,gb,Reino Unido,NaN
75,3605,79753,http://labs.data.scotland.gov.uk,2018-08-28 01:07:22,1208,gb,Reino Unido,NaN
82,3663,79811,http://opendata.wigan.gov.uk,2018-08-29 02:49:46,1412,gb,Reino Unido,ARCGIS
101,3851,80000,http://thedomainfo.com/open.glasgow.gov.uk,2018-08-30 12:21:38,2030,gb,Reino Unido,NaN
146,4145,80297,http://landregistry.data.gov.uk,2018-09-06 00:57:47,3555,gb,Reino Unido,NaN
170,4268,98520,http://dataportal.orr.gov.uk,2018-09-14 16:01:09,6099,gb,Reino Unido,NaN
193,4339,108552,https://www.openadmintools.com/en/www.nihe.gov.uk,2018-09-14 23:03:15,6369,gb,Reino Unido,NaN
206,4414,123043,https://data.westsuffolk.gov.uk,2018-09-15 08:28:13,6740,gb,Reino Unido,NaN
241,4752,191018,http://csw.data.gov.uk,2018-09-17 04:12:25,8517,gb,Reino Unido,NaN
286,5032,249552,https://opendata.camden.gov.uk,2018-09-19 14:58:09,10067,gb,Reino Unido,SOCRATA
295,5092,263195,https://digital-agenda-data.eu/data/factsheet....,2018-09-21 00:19:54,10448,gb,Reino Unido,NaN
305,5154,273036,http://www.transparency.essex-fire.gov.uk,2018-09-21 06:51:35,10724,gb,Reino Unido,NaN
307,5161,274195,http://datashare.colchester.gov.uk,2018-09-21 07:31:41,10755,gb,Reino Unido,NaN
332,5280,294888,http://data.bracknell-forest.gov.uk,2018-09-21 22:32:26,11273,gb,Reino Unido,NaN
339,5301,297841,http://data.hounslow.gov.uk,2018-09-22 00:09:04,11344,gb,Reino Unido,NaN
346,5332,305105,http://publicdata.landregistry.gov.uk,2018-09-22 04:41:05,11523,gb,Reino Unido,NaN
385,5527,350477,http://open.manchester.gov.uk,2018-09-23 07:47:46,12694,gb,Reino Unido,NaN
386,5530,351227,https://data.gov.uk,2018-09-23 08:13:11,12714,gb,Reino Unido,CKAN
394,5608,371179,http://cycling.data.tfl.gov.uk,2018-09-23 20:28:42,13277,gb,Reino Unido,NaN
396,5612,371844,http://data.scambs.gov.uk,2018-09-23 20:53:16,13296,gb,Reino Unido,NaN
404,5657,383128,http://unedddatacymru.gov.uk,2018-09-24 07:27:27,13600,gb,Reino Unido,NaN
420,5810,417931,https://www.opendatani.gov.uk,2018-09-25 11:35:27,14529,gb,Reino Unido,CKAN
475,6114,488518,https://opendata.cheshireeast.gov.uk,2018-09-28 00:01:40,16441,gb,Reino Unido,SOCRATA
494,6309,516596,http://openmappingdata.lambeth.gov.uk,2018-09-28 22:39:32,17161,gb,Reino Unido,ARCGIS
521,6440,550581,http://data.highways.gov.uk,2018-09-29 20:14:51,18052,gb,Reino Unido,NaN
588,6831,591999,https://openpolicy.blog.gov.uk,2018-09-30 22:21:48,19168,gb,Reino Unido,NaN
621,7071,636386,http://data.bassetlaw.gov.uk,2018-10-02 19:10:15,20364,gb,Reino Unido,NaN
629,7102,640089,http://www.grampiancaredata.gov.uk,2018-10-02 21:40:10,20459,gb,Reino Unido,NaN
662,7329,680727,https://data.birmingham.gov.uk,2018-10-04 07:52:27,21555,gb,Reino Unido,CKAN
698,7449,703828,https://cardtransactions.campaign.gov.uk,2018-10-05 07:45:33,22244,gb,Reino Unido,NaN
746,7629,730164,http://openrev.redditchbc.gov.uk,2018-10-08 03:47:26,23093,gb,Reino Unido,NaN
756,7687,735759,https://transformingtogether.blog.gov.uk,2018-10-08 06:18:44,23275,gb,Reino Unido,NaN
825,8132,801197,http://data.energynpsconsultation.decc.gov.uk,2018-10-09 12:35:15,25387,gb,Reino Unido,NaN
856,8414,825621,https://data.dundeecity.gov.uk,2018-10-11 00:12:59,26177,gb,Reino Unido,CKAN
883,8594,854499,https://data.london.gov.uk,2018-10-13 17:22:51,27111,gb,Reino Unido,CKAN

In [5]:
df_table_merge = pd.read_csv("../CSVs/coordinates_decimals.csv")

In [6]:
df_table_merge

,Unnamed: 0,Unnamed: 0.1,all,initials,latitude,longitude,country
0,0,0,<tr>\n<td>AD</td>\n<td>42.546245</td>\n<td>1.6...,ad,42.546245,1.60155,Andorra
1,1,1,<tr>\n<td>AE</td>\n<td>23.424076</td>\n<td>53....,ae,23.424076,53.84781,United Arab Emirates
2,2,2,<tr>\n<td>AF</td>\n<td>33.93911</td>\n<td>67.7...,af,33.939110,67.70995,Afghanistan
3,3,3,<tr>\n<td>AG</td>\n<td>17.060816</td>\n<td>-61...,ag,17.060816,-61.79642,Antigua and Barbuda
4,4,4,<tr>\n<td>AI</td>\n<td>18.220554</td>\n<td>-63...,ai,18.220554,-63.06861,Anguilla
5,5,5,<tr>\n<td>AL</td>\n<td>41.153332</td>\n<td>20....,al,41.153332,20.16833,Albania
6,6,6,<tr>\n<td>AM</td>\n<td>40.069099</td>\n<td>45....,am,40.069099,45.03818,Armenia
7,7,7,<tr>\n<td>AN</td>\n<td>12.226079</td>\n<td>-69...,an,12.226079,-69.06008,Netherlands Antilles
8,8,8,<tr>\n<td>AO</td>\n<td>-11.202692</td>\n<td>17...,ao,-11.202692,17.87388,Angola
9,9,9,<tr>\n<td>AQ</td>\n<td>-75.250973</td>\n<td>-0...,aq,-75.250973,-0.07138,Antarctica
10,10,10,<tr>\n<td>AR</td>\n<td>-38.416097</td>\n<td>-6...,ar,-38.416097,-63.61667,Argentina
11,11,11,<tr>\n<td>AS</td>\n<td>-14.270972</td>\n<td>-1...,as,-14.270972,-170.13221,American Samoa
12,12,12,<tr>\n<td>AT</td>\n<td>47.516231</td>\n<td>14....,at,47.516231,14.55007,Austria
13,13,13,<tr>\n<td>AU</td>\n<td>-25.274398</td>\n<td>13...,au,-25.274398,133.77513,Australia
14,14,14,<tr>\n<td>AW</td>\n<td>12.52111</td>\n<td>-69....,aw,12.521110,-69.96833,Aruba
15,15,15,<tr>\n<td>AZ</td>\n<td>40.143105</td>\n<td>47....,az,40.143105,47.57692,Azerbaijan
16,16,16,<tr>\n<td>BA</td>\n<td>43.915886</td>\n<td>17....,ba,43.915886,17.67907,Bosnia and Herzegovina
17,17,17,<tr>\n<td>BB</td>\n<td>13.193887</td>\n<td>-59...,bb,13.193887,-59.54319,Barbados
18,18,18,<tr>\n<td>BD</td>\n<td>23.684994</td>\n<td>90....,bd,23.684994,90.35633,Bangladesh
19,19,19,<tr>\n<td>BE</td>\n<td>50.503887</td>\n<td>4.4...,be,50.503887,4.46993,Belgium
20,20,20,<tr>\n<td>BF</td>\n<td>12.238333</td>\n<td>-1....,bf,12.238333,-1.56159,Burkina Faso
21,21,21,<tr>\n<td>BG</td>\n<td>42.733883</td>\n<td>25....,bg,42.733883,25.4858,Bulgaria
22,22,22,<tr>\n<td>BH</td>\n<td>25.930414</td>\n<td>50....,bh,25.930414,50.63777,Bahrain
23,23,23,<tr>\n<td>BI</td>\n<td>-3.373056</td>\n<td>29....,bi,-3.373056,29.91888,Burundi
24,24,24,<tr>\n<td>BJ</td>\n<td>9.30769</td>\n<td>2.315...,bj,9.307690,NaN,Benin
25,25,25,<tr>\n<td>BM</td>\n<td>32.321384</td>\n<td>-64...,bm,32.321384,-64.7573,Bermuda
26,26,26,<tr>\n<td>BN</td>\n<td>4.535277</td>\n<td>114....,bn,4.535277,114.72766,Brunei
27,27,27,<tr>\n<td>BO</td>\n<td>-16.290154</td>\n<td>-6...,bo,-16.290154,-63.58865,Bolivia
28,28,28,<tr>\n<td>BR</td>\n<td>-14.235004</td>\n<td>-5...,br,-14.235004,-51.9252,Brazil
29,29,29,<tr>\n<td>BS</td>\n<td>25.03428</td>\n<td>-77....,bs,25.034280,-77.3962,Bahamas
...,...,...,...,...,...,...,...
215,215,215,<tr>\n<td>TL</td>\n<td>-8.874217</td>\n<td>125...,tl,-8.874217,125.72753,Timor-Leste
216,216,216,<tr>\n<td>TM</td>\n<td>38.969719</td>\n<td>59....,tm,38.969719,59.55627,Turkmenistan
217,217,217,<tr>\n<td>TN</td>\n<td>33.886917</td>\n<td>9.5...,tn,33.886917,9.53749,Tunisia
218,218,218,<tr>\n<td>TO</td>\n<td>-21.178986</td>\n<td>-1...,to,-21.178986,-175.19824,Tonga
219,219,219,<tr>\n<td>TR</td>\n<td>38.963745</td>\n<td>35....,tr,38.963745,35.24332,Turkey
220,220,220,<tr>\n<td>TT</td>\n<td>10.691803</td>\n<td>-61...,tt,10.691803,-61.22250,Trinidad and Tobago
221,221,221,<tr>\n<td>TV</td>\n<td>-7.109535</td>\n<td>177...,tv,-7.109535,177.6493,Tuvalu
222,222,222,<tr>\n<td>TW</td>\n<td>23.69781</td>\n<td>120....,tw,23.697810,120.96051,Taiwan
223,223,223,<tr>\n<td>TZ</td>\n<td>-6.369028</td>\n<td>34....,tz,-6.369028,34.88882,Tanzania
224,224,224,<tr>\n<td>UA</td>\n<td>48.379433</td>\n<td>31....,ua,48.379433,31.1655,Ukraine
225,225,225,<tr>\n<td>UG</td>\n<td>1.373333</td>\n<td>32.2...,ug,1.373333,32.29027,Uganda
226,226,226,<tr>\n<td>UM</td>\n<td></td>\n<td></td>\n<td>U...,um,NaN,U.S. Minor Outlying Islands</t,NaN
227,227,227,<tr>\n<td>US</td>\n<td>37.09024</td>\n<td>-95....,us,37.090240,-95.71289,United States
228,228,228,<tr>\n<td>UY</td>\n<td>-32.522779</td>\n<td>-5...,uy,-32.522779,-55.76583,Uruguay
229,229,229,<tr>\n<td>UZ</td>\n<td>41.377491</td>\n<td>64....,uz,41.377491,64.58526,Uzbekistan
230,230,230,<tr>\n<td>VA</td>\n<td>41.902916</td>\n<td>12....,va,41.902916,12.45338,Vatican City
231,231,231,<tr>\n<td>VC</td>\n<td>12.984305</td>\n<td>-61...,vc,12.984305,-61.28722,Saint Vincent and the Grenadines
232,232,232,<tr>\n<td>VE</td>\n<td>6.42375</td>\n<td>-66.5...,ve,6.423750,NaN,Venezuela
233,233,233,<tr>\n<td>VG</td>\n<td>18.420695</td>\n<td>-64...,vg,18.420695,-64.63996,British Virgin Islands
234,234,234,<tr>\n<td>VI</td>\n<td>18.335765</td>\n<td>-64...,vi,18.335765,-64.89633,U.S. Virgin Islands
235,235,235,<tr>\n<td>VN</td>\n<td>14.058324</td>\n<td>108...,vn,14.058324,108.27719,Vietnam
236,236,236,<tr>\n<td>VU</td>\n<td>-15.376706</td>\n<td>16...,vu,-15.376706,166.95915,Vanuatu
237,237,237,<tr>\n<td>WF</td>\n<td>-13.768752</td>\n<td>-1...,wf,-13.768752,-177.15609,Wallis and Futuna
238,238,238,<tr>\n<td>WS</td>\n<td>-13.759029</td>\n<td>-1...,ws,-13.759029,-172.10462,Samoa
239,239,239,<tr>\n<td>XK</td>\n<td>42.602636</td>\n<td>20....,xk,42.602636,20.90297,Kosovo
240,240,240,<tr>\n<td>YE</td>\n<td>15.552727</td>\n<td>48....,ye,15.552727,48.51638,Yemen
241,241,241,<tr>\n<td>YT</td>\n<td>-12.8275</td>\n<td>45.1...,yt,-12.827500,45.16624,Mayotte
242,242,242,<tr>\n<td>ZA</td>\n<td>-30.559482</td>\n<td>22...,za,-30.559482,22.93750,South Africa
243,243,243,<tr>\n<td>ZM</td>\n<td>-13.133897</td>\n<td>27...,zm,-13.133897,27.84933,Zambia
244,244,244,<tr>\n<td>ZW</td>\n<td>-19.015438</td>\n<td>29...,zw,-19.015438,29.15485,Zimbabwe

In [7]:
df_merge = pd.merge(df_gov, df_table_merge, how="left",on="initials")

In [8]:
df_merge.drop(["Unnamed: 0_x","Unnamed: 0_y","Unnamed: 0.1","all","country_x"], axis=1,inplace=True)

In [9]:
df_merge.rename(columns={"country_y": "country"}, inplace=True)

In [10]:
df_merge

,id,url,date_catch,index_fraction,initials,platform_opendata,latitude,longitude,country
0,10392,https://freeflow.mdba.gov.au,2018-08-25 22:09:40,0,au,NaN,-25.274398,133.77513,Australia
1,63610,http://ftp4.de.freesbie.org/pub/misc/conferenc...,2018-08-30 06:59:55,1910,us,NaN,37.090240,-95.71289,United States
2,100473,https://handicap-free.nat.gov.tw,2018-09-01 07:12:49,2946,tw,NaN,23.697810,120.96051,Taiwan
3,118952,https://www.handicap-free.nat.gov.tw,2018-09-04 02:43:21,3435,tw,NaN,23.697810,120.96051,Taiwan
4,6176,http://data.environment.nsw.gov.au,2018-09-11 07:03:23,3793,au,NaN,-25.274398,133.77513,Australia
5,17602,https://www.transportation.gov/pr,2018-09-11 14:45:47,4096,us,NaN,37.090240,-95.71289,United States
6,21059,https://data.nj.gov/,2018-09-11 17:15:29,4191,us,NaN,37.090240,-95.71289,United States
7,21292,http://transportation.gov.ng,2018-09-11 17:24:33,4197,ng,NaN,9.081999,8.67527,Nigeria
8,23413,https://stereodata.nascom.nasa.gov/,2018-09-11 19:00:55,4253,us,NaN,37.090240,-95.71289,United States
9,24537,http://data.gov.gh,2018-09-11 19:48:43,4283,gh,NaN,7.946527,-1.02319,Ghana
10,25095,http://www.transparencia.sp.gov.br,2018-09-11 20:13:27,4299,br,NaN,-14.235004,-51.9252,Brazil
11,25659,https://data.illinois.gov/pa,2018-09-11 20:36:56,4315,us,NaN,37.090240,-95.71289,United States
12,25805,http://www.transparencia.cmsucupiradonorte.ma....,2018-09-11 20:42:43,4319,br,NaN,-14.235004,-51.9252,Brazil
13,26840,http://data.nconemap.gov/do,2018-09-11 21:29:40,4348,us,NaN,37.090240,-95.71289,United States
14,28295,http://transparencia.cariacica.es.gov.br,2018-09-11 22:24:45,4387,br,NaN,-14.235004,-51.9252,Brazil
15,30872,http://transalvador.salvador.ba.gov.br,2018-09-12 00:12:45,4460,br,NaN,-14.235004,-51.9252,Brazil
16,35368,http://stcsecom.transparencia.pb.gov.br,2018-09-12 10:32:14,4570,br,NaN,-14.235004,-51.9252,Brazil
17,36690,https://transactionalnetwork.pnnl.gov/,2018-09-12 11:21:37,4602,us,NaN,37.090240,-95.71289,United States
18,40941,https://www.openrecords.pa.gov/,2018-09-12 14:06:47,4705,us,NaN,37.090240,-95.71289,United States
19,42346,http://lab.environment.data.gov.au,2018-09-12 15:03:24,4740,au,NaN,-25.274398,133.77513,Australia
20,43647,http://transparencia.picos.pi.gov.br,2018-09-12 15:49:16,4771,br,NaN,-14.235004,-51.9252,Brazil
21,44629,https://guidance.data.gov.uk,2018-09-12 16:30:46,4795,gb,NaN,55.378051,-3.43597,United Kingdom
22,44661,http://transparencia.lagoadedentro.pb.gov.br,2018-09-12 16:31:59,4796,br,NaN,-14.235004,-51.9252,Brazil
23,46047,http://transparencia.causp.gov.br,2018-09-12 17:23:49,4831,br,NaN,-14.235004,-51.9252,Brazil
24,46929,https://www.thetransat.com/venues/view/www.ply...,2018-09-12 18:02:03,4854,gb,NaN,55.378051,-3.43597,United Kingdom
25,47069,http://odc.open.gov.ru,2018-09-12 18:06:39,4857,ru,NaN,61.524010,105.31875,Russia
26,47588,http://data.treasury.gov/Fe,2018-09-12 18:27:55,4870,us,NaN,37.090240,-95.71289,United States
27,53417,https://www.data.gov/fo,2018-09-12 22:17:15,5011,us,NaN,37.090240,-95.71289,United States
28,56280,http://waterdata.azdeq.gov/AZ,2018-09-13 10:44:24,5081,us,NaN,37.090240,-95.71289,United States
29,56965,http://open-storage-conference.nstm.gov.tw,2018-09-13 11:12:14,5098,tw,NaN,23.697810,120.96051,Taiwan
...,...,...,...,...,...,...,...,...,...
869,836885,http://transparencia.centralina.mg.gov.br,2018-10-11 04:56:46,26538,br,NaN,-14.235004,-51.9252,Brazil
870,837606,https://data.tucsonaz.gov/,2018-10-11 05:14:55,26562,us,NaN,37.090240,-95.71289,United States
871,838266,http://www.terminaldetransporte.gov.co,2018-10-11 05:29:37,26582,co,NaN,4.570868,-74.29733,Colombia
872,839008,https://data.macoupincountyil.gov/,2018-10-11 05:48:51,26606,us,NaN,37.090240,-95.71289,United States
873,839432,http://data.dg.gov.cn,2018-10-11 05:59:18,26620,cn,NaN,35.861660,104.19539,China
874,839746,https://data.monroecounty-fl.gov/,2018-10-11 06:07:26,26630,us,NaN,37.090240,-95.71289,United States
875,840259,https://data.gov.bc,2018-10-11 06:18:59,26646,bc,NaN,NaN,NaN,NaN
876,842489,https://www.transportation.virginia.gov/ag,2018-10-11 07:12:32,26717,us,NaN,37.090240,-95.71289,United States
877,843800,http://transportation.lagosstate.gov.ng,2018-10-11 07:46:13,26760,ng,NaN,9.081999,8.67527,Nigeria
878,844330,https://www.transportation.virginia.gov/re,2018-10-11 07:59:15,26777,us,NaN,37.090240,-95.71289,United States
879,846449,http://portaltransparencia.gov.br,2018-10-11 08:50:24,26845,br,NaN,-14.235004,-51.9252,Brazil
880,846943,https://digitalanddata.blog.gov.wa,2018-10-11 09:00:55,26859,wa,NaN,NaN,NaN,NaN
881,847573,https://ncsesdata.nsf.gov/pr,2018-10-11 09:16:04,26879,us,NaN,37.090240,-95.71289,United States
882,853500,https://www.transportation.gov/re,2018-10-13 16:57:55,27078,us,NaN,37.090240,-95.71289,United States
883,854499,https://data.london.gov.uk,2018-10-13 17:22:51,27111,gb,CKAN,55.378051,-3.43597,United Kingdom
884,855243,https://www.transportation.gov/br,2018-10-13 17:41:50,27136,us,NaN,37.090240,-95.71289,United States
885,859257,https://transparencia.areia.pb.gov.br,2018-10-13 19:23:48,27274,br,NaN,-14.235004,-51.9252,Brazil
886,859683,http://www.transport.gov.mt,2018-10-13 19:32:47,27287,mt,NaN,35.937496,14.37541,Malta
887,862639,http://data.motcmpb.gov.tw,2018-10-13 20:53:19,27385,tw,NaN,23.697810,120.96051,Taiwan
888,863527,http://www3.transparencia.gov.br,2018-10-13 21:16:27,27417,br,NaN,-14.235004,-51.9252,Brazil
889,865610,http://opendata.fortsmithar.gov/,2018-10-13 22:08:01,27487,us,CKAN,37.090240,-95.71289,United States
890,866366,http://pnass.datasus.gov.br,2018-10-13 22:26:23,27512,br,NaN,-14.235004,-51.9252,Brazil
891,866703,http://transport.cwp.govt.n,2018-10-13 22:37:46,27523,NaN,NaN,NaN,NaN,NaN
892,867367,https://www.accessdata.fda.gov/sc,2018-10-13 22:55:46,27547,us,NaN,37.090240,-95.71289,United States
893,868122,http://transwa.wa.gov.au,2018-10-13 23:14:00,27572,au,NaN,-25.274398,133.77513,Australia
894,868688,http://data.gov.sp,2018-10-13 23:27:33,27591,sp,NaN,NaN,NaN,NaN
895,868715,https://www.transport.gov.sc,2018-10-13 23:28:15,27592,sc,NaN,-4.679574,55.49197,Seychelles
896,870348,http://transparencia.carneirinho.mg.gov.br,2018-10-14 00:06:35,27643,br,NaN,-14.235004,-51.9252,Brazil
897,870356,https://data-archive.nimh.nih.gov/,2018-10-14 00:06:35,27643,us,NaN,37.090240,-95.71289,United States
898,870417,https://data.oregon.gov/Re,2018-10-14 00:08:06,27645,us,NaN,37.090240,-95.71289,United States

In [12]:
# devolve os valores de plataforma_opendata que forem diferentes de None
df_merge.query('platform_opendata == platform_opendata')

,id,url,date_catch,index_fraction,initials,platform_opendata,latitude,longitude,country
48,79478,http://opendata.suffolkcountyny.gov/,2018-08-25 12:20:12,0,us,ARCGIS,37.090240,-95.71289,United States
59,79661,https://data.bloomington.in.gov/,2018-08-26 11:30:18,668,us,CKAN,37.090240,-95.71289,United States
64,79692,https://data.cdc.gov.tw,2018-08-26 20:25:58,876,tw,CKAN,23.697810,120.96051,Taiwan
82,79811,http://opendata.wigan.gov.uk,2018-08-29 02:49:46,1412,gb,ARCGIS,55.378051,-3.43597,United Kingdom
108,80092,http://opendata.hccg.gov.tw,2018-08-31 04:38:28,2374,tw,CKAN,23.697810,120.96051,Taiwan
149,80319,https://www.opencrete.gov.gr,2018-09-06 12:24:28,3628,gr,CKAN,39.074208,21.82431,Greece
150,80323,http://opendata.slocounty.ca.gov/,2018-09-06 13:03:40,3642,us,ARCGIS,37.090240,-95.71289,United States
187,105859,http://data.outdoornebraska.gov/,2018-09-14 21:08:54,6295,us,ARCGIS,37.090240,-95.71289,United States
263,220194,https://www.data.act.gov.au,2018-09-18 18:26:30,9282,au,SOCRATA,-25.274398,133.77513,Australia
270,229045,http://opendata.firstmap.delaware.gov/,2018-09-19 00:17:26,9507,us,ARCGIS,37.090240,-95.71289,United States
286,249552,https://opendata.camden.gov.uk,2018-09-19 14:58:09,10067,gb,SOCRATA,55.378051,-3.43597,United Kingdom
324,288701,http://data.gov.ua,2018-09-21 19:08:00,11120,ua,CKAN,48.379433,31.1655,Ukraine
326,293195,http://data.gov.ro,2018-09-21 21:35:26,11231,ro,CKAN,45.943161,24.9667,Romania
335,296147,https://data.gov.au,2018-09-21 23:12:58,11303,au,CKAN,-25.274398,133.77513,Australia
357,319573,http://data.roanokecountyva.gov/,2018-09-22 14:03:15,11886,us,ARCGIS,37.090240,-95.71289,United States
364,326124,https://data.melbourne.vic.gov.au,2018-09-22 17:31:08,12048,au,SOCRATA,-25.274398,133.77513,Australia
369,328018,https://www.data.vic.gov.au,2018-09-22 18:32:56,12096,au,CKAN,-25.274398,133.77513,Australia
375,334525,https://catalogue.data.wa.gov.au,2018-09-22 22:08:29,12262,au,CKAN,-25.274398,133.77513,Australia
386,351227,https://data.gov.uk,2018-09-23 08:13:11,12714,gb,CKAN,55.378051,-3.43597,United Kingdom
390,359139,https://data.gov.sk,2018-09-23 12:59:57,12931,sk,CKAN,48.669026,19.69902,Slovakia
420,417931,https://www.opendatani.gov.uk,2018-09-25 11:35:27,14529,gb,CKAN,55.378051,-3.43597,United Kingdom
421,420023,http://data.taichung.gov.tw,2018-09-25 13:14:10,14590,tw,CKAN,23.697810,120.96051,Taiwan
424,428295,http://opendata.columbus.gov/,2018-09-25 18:45:09,14814,us,ARCGIS,37.090240,-95.71289,United States
456,474517,http://datalb.longbeach.gov/,2018-09-27 15:43:13,16069,us,ARCGIS,37.090240,-95.71289,United States
475,488518,https://opendata.cheshireeast.gov.uk,2018-09-28 00:01:40,16441,gb,SOCRATA,55.378051,-3.43597,United Kingdom
494,516596,http://openmappingdata.lambeth.gov.uk,2018-09-28 22:39:32,17161,gb,ARCGIS,55.378051,-3.43597,United Kingdom
530,555555,http://opendata.yakimawa.gov/,2018-09-29 22:59:14,18178,us,ARCGIS,37.090240,-95.71289,United States
577,581762,http://www.data.gov.md,2018-09-30 14:33:16,18876,md,CKAN,47.411631,28.36988,Moldova
606,618844,https://openpaymentsdata.cms.gov/,2018-10-02 04:07:17,19907,us,SOCRATA,37.090240,-95.71289,United States
662,680727,https://data.birmingham.gov.uk,2018-10-04 07:52:27,21555,gb,CKAN,55.378051,-3.43597,United Kingdom
744,728665,http://dados.transportes.gov.br,2018-10-08 03:07:49,23044,br,CKAN,-14.235004,-51.9252,Brazil
759,736766,http://www.data.gov.gr,2018-10-08 06:43:07,23304,gr,CKAN,39.074208,21.82431,Greece
802,773183,http://opendata.e-land.gov.tw,2018-10-08 22:48:46,24458,tw,CKAN,23.697810,120.96051,Taiwan
823,800913,http://data.belmont.gov/,2018-10-09 12:27:02,25377,us,ARCGIS,37.090240,-95.71289,United States
838,815358,http://data.gov.md,2018-10-10 19:57:32,25845,md,CKAN,47.411631,28.36988,Moldova
845,821760,http://geodata.vermont.gov/,2018-10-10 22:39:45,26056,us,ARCGIS,37.090240,-95.71289,United States
847,823220,http://opendata.dc.gov/,2018-10-10 23:16:07,26103,us,ARCGIS,37.090240,-95.71289,United States
854,824932,http://anrgeodata.vermont.gov/,2018-10-10 23:54:26,26155,us,ARCGIS,37.090240,-95.71289,United States
856,825621,https://data.dundeecity.gov.uk,2018-10-11 00:12:59,26177,gb,CKAN,55.378051,-3.43597,United Kingdom
883,854499,https://data.london.gov.uk,2018-10-13 17:22:51,27111,gb,CKAN,55.378051,-3.43597,United Kingdom
889,865610,http://opendata.fortsmithar.gov/,2018-10-13 22:08:01,27487,us,CKAN,37.090240,-95.71289,United States

In [14]:
# verifica se os dados dos Estados Unidos estão aparecendo
palavra = "us"
df_merge.query("initials in @palavra")

,id,url,date_catch,index_fraction,initials,platform_opendata,latitude,longitude,country
1,63610,http://ftp4.de.freesbie.org/pub/misc/conferenc...,2018-08-30 06:59:55,1910,us,NaN,37.09024,-95.71289,United States
5,17602,https://www.transportation.gov/pr,2018-09-11 14:45:47,4096,us,NaN,37.09024,-95.71289,United States
6,21059,https://data.nj.gov/,2018-09-11 17:15:29,4191,us,NaN,37.09024,-95.71289,United States
8,23413,https://stereodata.nascom.nasa.gov/,2018-09-11 19:00:55,4253,us,NaN,37.09024,-95.71289,United States
11,25659,https://data.illinois.gov/pa,2018-09-11 20:36:56,4315,us,NaN,37.09024,-95.71289,United States
13,26840,http://data.nconemap.gov/do,2018-09-11 21:29:40,4348,us,NaN,37.09024,-95.71289,United States
17,36690,https://transactionalnetwork.pnnl.gov/,2018-09-12 11:21:37,4602,us,NaN,37.09024,-95.71289,United States
18,40941,https://www.openrecords.pa.gov/,2018-09-12 14:06:47,4705,us,NaN,37.09024,-95.71289,United States
26,47588,http://data.treasury.gov/Fe,2018-09-12 18:27:55,4870,us,NaN,37.09024,-95.71289,United States
27,53417,https://www.data.gov/fo,2018-09-12 22:17:15,5011,us,NaN,37.09024,-95.71289,United States
28,56280,http://waterdata.azdeq.gov/AZ,2018-09-13 10:44:24,5081,us,NaN,37.09024,-95.71289,United States
33,61074,http://transition.ne.gov/,2018-09-13 14:02:05,5200,us,NaN,37.09024,-95.71289,United States
34,65132,https://data.maine.gov/,2018-09-13 16:50:55,5303,us,NaN,37.09024,-95.71289,United States
38,76825,https://data.mesaaz.gov/,2018-09-14 00:36:12,5596,us,NaN,37.09024,-95.71289,United States
40,78536,http://vtrans.vermont.gov/fi,2018-09-11 03:50:58,3670,us,NaN,37.09024,-95.71289,United States
42,78561,http://vtrans.vermont.gov/pr,2018-09-11 07:14:52,3802,us,NaN,37.09024,-95.71289,United States
48,79478,http://opendata.suffolkcountyny.gov/,2018-08-25 12:20:12,0,us,ARCGIS,37.09024,-95.71289,United States
49,79492,https://www.openadmintools.com/en/factfinder2....,2018-08-25 13:25:59,0,us,NaN,37.09024,-95.71289,United States
50,79495,https://data.sandiego.gov/da,2018-08-25 13:59:06,0,us,NaN,37.09024,-95.71289,United States
51,79507,https://data.sandiego.gov/,2018-08-25 15:48:08,0,us,NaN,37.09024,-95.71289,United States
56,79629,https://data.sandiego.gov/se,2018-08-26 05:19:39,0,us,NaN,37.09024,-95.71289,United States
57,79639,https://data.sandiego.gov/st,2018-08-26 06:05:28,0,us,NaN,37.09024,-95.71289,United States
59,79661,https://data.bloomington.in.gov/,2018-08-26 11:30:18,668,us,CKAN,37.09024,-95.71289,United States
61,79665,https://waterdata.usgs.gov/la,2018-08-26 12:30:28,693,us,NaN,37.09024,-95.71289,United States
62,79675,https://developer.earthdata.nasa.gov/,2018-08-26 16:04:17,768,us,NaN,37.09024,-95.71289,United States
65,79693,https://www.openadmintools.com/en/www.odessa-t...,2018-08-26 20:27:51,877,us,NaN,37.09024,-95.71289,United States
66,79699,http://openbudget.ct.gov/,2018-08-26 21:57:17,912,us,NaN,37.09024,-95.71289,United States
68,79725,https://datavizpublic.in.gov/,2018-08-27 05:35:19,1074,us,NaN,37.09024,-95.71289,United States
76,79761,https://henlopenacres.delaware.gov/ev,2018-08-28 10:58:05,1249,us,NaN,37.09024,-95.71289,United States
78,79765,https://henlopenacres.delaware.gov/20,2018-08-28 11:31:22,1262,us,NaN,37.09024,-95.71289,United States
...,...,...,...,...,...,...,...,...,...
842,817174,https://waterdata.usgs.gov/wa,2018-10-10 20:42:49,25903,us,NaN,37.09024,-95.71289,United States
845,821760,http://geodata.vermont.gov/,2018-10-10 22:39:45,26056,us,ARCGIS,37.09024,-95.71289,United States
846,822321,https://data.pa.gov/,2018-10-10 22:52:27,26074,us,NaN,37.09024,-95.71289,United States
847,823220,http://opendata.dc.gov/,2018-10-10 23:16:07,26103,us,ARCGIS,37.09024,-95.71289,United States
848,823300,https://eddataexpress.ed.gov/da,2018-10-10 23:17:37,26105,us,NaN,37.09024,-95.71289,United States
850,824148,http://datamart.business.transportation.ky.gov/ED,2018-10-10 23:36:54,26131,us,NaN,37.09024,-95.71289,United States
852,824409,https://eddataexpress.ed.gov/st,2018-10-10 23:42:44,26139,us,NaN,37.09024,-95.71289,United States
854,824932,http://anrgeodata.vermont.gov/,2018-10-10 23:54:26,26155,us,ARCGIS,37.09024,-95.71289,United States
855,825514,https://cdn.earthdata.nasa.gov/is,2018-10-11 00:10:10,26173,us,NaN,37.09024,-95.71289,United States
857,826001,https://www.transportation.gov/fe,2018-10-11 00:21:56,26189,us,NaN,37.09024,-95.71289,United States
858,829328,http://hoosierdata.in.gov/in,2018-10-11 01:42:54,26292,us,NaN,37.09024,-95.71289,United States
860,829810,https://earthdata.nasa.gov/,2018-10-11 01:56:22,26308,us,NaN,37.09024,-95.71289,United States
861,830667,https://www.transportation.virginia.gov/,2018-10-11 02:18:53,26335,us,NaN,37.09024,-95.71289,United States
863,831031,http://healthdata.vermont.gov/,2018-10-11 02:27:44,26347,us,NaN,37.09024,-95.71289,United States
864,831345,https://www.transportation.virginia.gov/we,2018-10-11 02:36:17,26357,us,NaN,37.09024,-95.71289,United States
865,832674,http://hoosierdata.in.gov/,2018-10-11 03:09:26,26400,us,NaN,37.09024,-95.71289,United States
866,832765,https://www.transportation.virginia.gov/ab,2018-10-11 03:11:17,26402,us,NaN,37.09024,-95.71289,United States
867,833777,https://waterdata.usgs.gov/nw,2018-10-11 03:38:24,26436,us,NaN,37.09024,-95.71289,United States
870,837606,https://data.tucsonaz.gov/,2018-10-11 05:14:55,26562,us,NaN,37.09024,-95.71289,United States
872,839008,https://data.macoupincountyil.gov/,2018-10-11 05:48:51,26606,us,NaN,37.09024,-95.71289,United States
874,839746,https://data.monroecounty-fl.gov/,2018-10-11 06:07:26,26630,us,NaN,37.09024,-95.71289,United States
876,842489,https://www.transportation.virginia.gov/ag,2018-10-11 07:12:32,26717,us,NaN,37.09024,-95.71289,United States
878,844330,https://www.transportation.virginia.gov/re,2018-10-11 07:59:15,26777,us,NaN,37.09024,-95.71289,United States
881,847573,https://ncsesdata.nsf.gov/pr,2018-10-11 09:16:04,26879,us,NaN,37.09024,-95.71289,United States
882,853500,https://www.transportation.gov/re,2018-10-13 16:57:55,27078,us,NaN,37.09024,-95.71289,United States
884,855243,https://www.transportation.gov/br,2018-10-13 17:41:50,27136,us,NaN,37.09024,-95.71289,United States
889,865610,http://opendata.fortsmithar.gov/,2018-10-13 22:08:01,27487,us,CKAN,37.09024,-95.71289,United States
892,867367,https://www.accessdata.fda.gov/sc,2018-10-13 22:55:46,27547,us,NaN,37.09024,-95.71289,United States
897,870356,https://data-archive.nimh.nih.gov/,2018-10-14 00:06:35,27643,us,NaN,37.09024,-95.71289,United States
898,870417,https://data.oregon.gov/Re,2018-10-14 00:08:06,27645,us,NaN,37.09024,-95.71289,United States

In [17]:
df_merge.to_csv("../CSVs/table_second_step_merge_signatures_coordinates.csv")

In [16]:
gc.collect()

19